CREATE OR REPLACE VIEW VIEW_DEVOL_RESUMO_FATURAVULSA AS
SELECT PCNFENT.CODFILIAL,
 PCUSUARI.CODSUPERVISOR,
 PCUSUARI.CODUSUR,
 PCMOV.CODUSUR CODUSURMOV,
 COALESCE(PCMOVCOMPLE.CODSUPERVISOR,
 (SELECT CODSUPERVISOR
 FROM PCUSUARI
 WHERE CODUSUR = PCMOV.CODUSUR
 AND ROWNUM = 1)) CODSUPERVMOV,
 (SELECT S.CODCOORDENADOR
 FROM PCSUPERV S
 WHERE S.CODSUPERVISOR =
 COALESCE(PCMOVCOMPLE.CODSUPERVISOR,
 (SELECT CODSUPERVISOR
 FROM PCUSUARI
 WHERE CODUSUR = PCMOV.CODUSUR
 AND ROWNUM = 1))) CODCOORDENADOR, -- COORDENADOR DO SUPERVISOR DA MOVIMENTAÇÃO
 (SELECT DECODE(S.CODCOORDENADOR,
 NULL,
 S.CODGERENTE,
 (SELECT C.CODGERENTE
 FROM PCCOORDENADORVENDA C
 WHERE C.CODIGO = S.CODCOORDENADOR))
 FROM PCSUPERV S
 WHERE S.CODSUPERVISOR =
 COALESCE(PCMOVCOMPLE.CODSUPERVISOR,
 (SELECT CODSUPERVISOR
 FROM PCUSUARI
 WHERE CODUSUR = PCMOV.CODUSUR
 AND ROWNUM = 1))) CODGERENTELOCAL, -- GERENTE LOCAL DO COORDENADOR OU DO SUPERVISOR DA MOVIMENTAÇÃO
 (SELECT GR.CODGERENTE
 FROM PCSUPERV S, PCGERENTE GL, PCGERENTE GR
 WHERE COALESCE(PCMOVCOMPLE.CODSUPERVISOR,
 (SELECT CODSUPERVISOR
 FROM PCUSUARI
 WHERE CODUSUR = PCMOV.CODUSUR
 AND ROWNUM = 1)) = S.CODSUPERVISOR
 AND DECODE(S.CODCOORDENADOR,
 NULL,
 S.CODGERENTE,
 (SELECT C.CODGERENTE
 FROM PCCOORDENADORVENDA C
 WHERE C.CODIGO = S.CODCOORDENADOR)) = GL.CODGERENTE
 AND GL.CODGERENTESUPERIOR = GR.CODGERENTE(+)) CODGERENTEREGIONAL, -- GERENTE REGIONAL DO GERENTE LOCAL DO COORDENADOR OU DO SUPERVISOR DA MOVIMENTAÇÃO
 (SELECT GR.CODGERENTESUPERIOR
 FROM PCSUPERV S, PCGERENTE GL, PCGERENTE GR
 WHERE COALESCE(PCMOVCOMPLE.CODSUPERVISOR,
 (SELECT CODSUPERVISOR
 FROM PCUSUARI
 WHERE CODUSUR = PCMOV.CODUSUR
 AND ROWNUM = 1)) = S.CODSUPERVISOR
 AND DECODE(S.CODCOORDENADOR,
 NULL,
 S.CODGERENTE,
 (SELECT C.CODGERENTE
 FROM PCCOORDENADORVENDA C
 WHERE C.CODIGO = S.CODCOORDENADOR)) = GL.CODGERENTE
 AND GL.CODGERENTESUPERIOR = GR.CODGERENTE(+)) CODGERENTENACIONAL, -- GERENTE NACIONAL DO GERENTE REGIONAL DO GERENTE LOCAL DO COORDENADOR OU DO SUPERVISOR DA MOVIMENTAÇÃO
 (SELECT GN.CODGERENTESUPERIOR
 FROM PCSUPERV S, PCGERENTE GL, PCGERENTE GR, PCGERENTE GN
 WHERE COALESCE(PCMOVCOMPLE.CODSUPERVISOR,
 (SELECT CODSUPERVISOR
 FROM PCUSUARI
 WHERE CODUSUR = PCMOV.CODUSUR
 AND ROWNUM = 1)) = S.CODSUPERVISOR
 AND DECODE(S.CODCOORDENADOR,
 NULL,
 S.CODGERENTE,
 (SELECT C.CODGERENTE
 FROM PCCOORDENADORVENDA C
 WHERE C.CODIGO = S.CODCOORDENADOR)) = GL.CODGERENTE
 AND GL.CODGERENTESUPERIOR = GR.CODGERENTE(+)
 AND GR.CODGERENTESUPERIOR = GN.CODGERENTE(+)) CODDIRETOR, -- DIRETOR DO GERENTE NACIONAL DO GERENTE REGIONAL DO GERENTE LOCAL DO COORDENADOR OU DO SUPERVISOR DA MOVIMENTAÇÃO
 (NVL(PCMOV.QT, 0) *
 (NVL(PCMOV.PUNIT, 0) + NVL(PCMOV.VLFRETE, 0) +
 NVL(PCMOV.VLOUTRASDESP, 0) + NVL(PCMOV.VLFRETE_RATEIO, 0) +
 NVL(PCMOV.VLOUTROS, 0) - NVL(PCMOV.VLREPASSE, 0))) VLTOTAL,
 PCNFENT.DTENT,
 PCNFENT.UF,
 (PCMOV.QT * PCMOV.CUSTOFIN) VLDEVCMVAVULSAI,
 NVL(PCMOV.QT, 0) *
 (NVL(PCMOV.ST, 0) + NVL(PCMOVCOMPLE.VLSTTRANSFCD, 0)) VLST,
 NVL(PCMOV.VLIPI, 0) * NVL(PCMOV.QT, 0) VLIPI,
 NVL(ROUND(PCMOV.QT * PCMOV.VLREPASSE, 2), 0) VLREPASSE,
 PCPRODUT.CODMARCA,
 PCPRODUT.CODLINHAPROD,
 PCMOV.CODEPTO,
 PCMOV.CODPROD,
 PCMOV.CODPLPAG,
 PCMOV.NUMREGIAO,
 PCCLIENT.CODPRACA,
 PCPRACA.ROTA,
 PCCLIENT.VIP,
 PCCLIENT.CODATV1 CODATIV,
 NVL(PCATIVI.CODATIVPRINC, PCATIVI.CODATIV) CODATIVPRINC,
 (PCMOV.QT * PCMOV.CUSTOFIN) VLCUSTOFIN,
 PCMOV.QT,
 (NVL(PCMOV.QT, 0) *
 (NVL(PCMOV.PUNIT, 0) + NVL(PCMOV.VLFRETE, 0) +
 NVL(PCMOV.VLOUTRASDESP, 0) + NVL(PCMOV.VLFRETE_RATEIO, 0) +
 NVL(PCMOV.VLOUTROS, 0) - NVL(PCMOV.VLREPASSE, 0))) VLDEVOLUCAO, /*PCNFENT.VLOUTRAS,
 PCNFENT.VLFRETE,*/
 ROUND(NVL(PCMOV.VLOUTROS, 0) * NVL(PCMOV.QT, 0), 2) VLOUTRAS,
 ROUND(NVL(PCMOV.VLFRETE, 0) * NVL(PCMOV.QT, 0), 2) VLFRETE,
 SUBSTR(PCSUPERV.NOME, 1, 40) SUPERV,
 SUBSTR(PCUSUARI.NOME, 1, 40) NOME,
 (NVL(PCMOV.PESOBRUTO, PCPRODUT.PESOBRUTO) * NVL(PCMOV.QT, 0)) TOTPESO,
 PCNFENT.NUMNOTA,
 PCNFENT.NUMTRANSENT,
 PCNFENT.CODDEVOL,
 PCMOV.CODDEVOL DEVOLITEM,
 SUBSTR(PCTABDEV.MOTIVO, 1, 30) MOTIVO,
 SUBSTR(PCCLIENT.CLIENTE, 1, 40) CLIENTE,
 PCTABDEV2.MOTIVO MOTIVO2,
 PCCLIENT.CODCLI,
 PCNFENT.CODMOTORISTADEVOL,
 PCPRODUT.CODFORNEC,
 NVL(FORNEC_PROD.CODFORNECPRINC, FORNEC_PROD.CODFORNEC) CODFORNECPRINC,
 SUBSTR(PCPRODUT.EMBALAGEM, 1, 12) EMBALAGEM,
 PCPRODUT.UNIDADE,
 SUBSTR(PCPRODUT.DESCRICAO, 1, 40) DESCRICAO,
 (CASE
 WHEN NVL(PCMOV.PBONIFIC, 0) > 0 THEN
 'S'
 ELSE
 'N'
 END) AS BONIFICADO,
 PCPRODUT.CODSEC,
 PCPRODUT.NUMORIGINAL,
 PCPRODUT.CODAUXILIAR,
 PCCLIENT.IEENT,
 PCCLIENT.ESTENT,
 PCCLIENT.CGCENT,
 PCCLIENT.MUNICENT,
 PCPRODUT.CODCATEGORIA,
 PCPRODUT.CODSUBCATEGORIA,
 0 AS NUMTRANSVENDA,
 PCMOV.NUMSEQ,
 PCNFENT.ESPECIE,
 (CASE
 WHEN NVL(PCNFENT.GERANFDEVCLI, 'N') = 'N' THEN
 100
 ELSE
 PCNFENT.SITUACAONFE
 END) AS SITUACAONFE,
 PCMOV.CODFORNEC AS CODFORNECMOV
 FROM PCNFENT,
 PCUSUARI,
 PCESTCOM,
 PCMOV,
 PCCLIENT,
 PCATIVI,
 PCPRACA,
 PCSUPERV,
 PCPRODUT,
 PCFORNEC FORNEC_PROD,
 PCTABDEV,
 PCTABDEV PCTABDEV2,
 PCMOVCOMPLE
 WHERE PCNFENT.TIPODESCARGA NOT IN ('C', 'D', '8')
 AND PCNFENT.CODUSURDEVOL = PCUSUARI.CODUSUR
 AND PCNFENT.CODFORNEC = PCCLIENT.CODCLI
 AND PCCLIENT.CODATV1 = PCATIVI.CODATIV
 AND PCCLIENT.CODPRACA = PCPRACA.CODPRACA
 AND NVL(PCNFENT.OBS, 'X') <> 'NF CANCELADA'
 AND PCESTCOM.NUMTRANSENT = PCNFENT.NUMTRANSENT
 AND PCESTCOM.NUMTRANSENT = PCMOV.NUMTRANSENT
 AND NVL(PCESTCOM.NUMTRANSVENDA, 0) = 0
 AND PCMOV.CODOPER = 'ED'
 AND NVL(PCNFENT.ESPECIE, 'X') <> 'OE'
 AND PCSUPERV.CODSUPERVISOR = PCUSUARI.CODSUPERVISOR
 AND PCMOV.CODPROD = PCPRODUT.CODPROD
 AND PCPRODUT.CODFORNEC = FORNEC_PROD.CODFORNEC
 AND PCMOV.NUMTRANSITEM = PCMOVCOMPLE.NUMTRANSITEM(+)
 AND PCNFENT.CODDEVOL = PCTABDEV.CODDEVOL(+)
 AND PCMOV.CODDEVOL = PCTABDEV2.CODDEVOL(+)
 AND PCNFENT.DTENT >= (SELECT MIN(DTENT) FROM PCNFENT)
 AND PCMOV.DTMOV >= (SELECT MIN(DTMOV) FROM PCMOV)
 AND NVL(PCNFENT.TIPOMOVGARANTIA, -1) = -1
