--CRIAÇÃO DA TABELA DE LOG
CREATE TABLE TPLOGDESCONTOINDEV (	
				 
                 CODEMITENTE INT
				, INT
				,CODCLINEW INT
                ,CODCLIOLD INT
				,CODUSURPADRAONEW INT
                ,CODUSURPADRAOOLD INT
                ,DATAALTER DATE
			    ,ENVIAFVNEW VARCHAR2(1)
                ,ENVIAFVOLD VARCHAR2(1)
				,MAQUINA VARCHAR2(80)
			    ,USUARIO VARCHAR2(80)
				,PROGRAM VARCHAR2(80)
			    ,OPERACAO VARCHAR2(1)
                  );
                                     
---- FIM CREATE TABLE      

CREATE OR REPLACE TRIGGER TRG_TPPEDDESCITEM

BEFORE --ANTES-BEFORE /DEPOIS-AFTER

INSERT ON PCPEDI     /*--AÇÃO*/ 
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
	
DECLARE

  V_CODMONITOR INT;
  V_PERCDESC_CAMPANHA NUMBER (12,10);
  V_CODDESCONTO INT;
  
BEGIN

SELECT CODMONITOR INTO V_CODMONITOR FROM PCUSUARI WHERE CODUSUR = :NEW.CODUSUR;

IF V_CODMONITOR IN (11,14) THEN 

                  IF NVL(:NEW.CODDESCONTO,0) = 0 THEN
                     SELECT NVL((SELECT CODDESCONTO FROM PCORCAVENDAI WHERE NUMORCA = :NEW.NUMPED AND CODPROD = :NEW.CODPROD),0) INTO V_CODDESCONTO FROM DUAL;
                  ELSE V_CODDESCONTO := :NEW.CODDESCONTO;
                  END IF;
				  
				  IF V_CODDESCONTO > 0 THEN
                     SELECT PERCDESC INTO V_PERCDESC_CAMPANHA FROM PCDESCONTO WHERE CODDESCONTO = V_CODDESCONTO;
                  ELSE V_PERCDESC_CAMPANHA := 0;
                  END IF;

                  IF V_CODDESCONTO = 0 AND :NEW.PERDESC > 0 AND :NEW.QT > 0 AND :NEW.PORIGINAL > 0 THEN
                     RAISE_APPLICATION_ERROR(-20001,('Desconto não vinculado a política de desconto.'));  
                  END IF;
   
                  IF V_CODDESCONTO > 0 AND NVL(:NEW.PERDESC,0) > (V_PERCDESC_CAMPANHA + 1) AND :NEW.QT > 0 AND :NEW.PORIGINAL > 0 THEN 
                     RAISE_APPLICATION_ERROR(-20001,('Desconto aplicado maior que o desconto da campanha.'));
                  END IF;   
END IF;

END;
