CREATE OR REPLACE TRIGGER TRG_TP_BLOQINATIVIDADECLIENTE
BEFORE INSERT ON PCCLIENT
FOR EACH row
DECLARE
V_TIPOFJ PCCLIENT.TIPOFJ%TYPE;
V_BLOQUEIOINATIVIDADE PCCLIENT.BLOQUEIOINATIVIDADE%TYPE;
BEGIN
V_TIPOFJ := :NEW.TIPOFJ;
V_BLOQUEIOINATIVIDADE := :NEW.BLOQUEIOINATIVIDADE;
  IF V_TIPOFJ = 'F' AND V_BLOQUEIOINATIVIDADE = 'S' THEN
     :NEW.BLOQUEIOINATIVIDADE := 'N';
  END IF; 
  	  EXCEPTION 
			WHEN OTHERS THEN  -- SE QUALQUER ERRO OCORRER 
			DBMS_OUTPUT.PUT_LINE('Erro na execução da TRIGGER.');
			DBMS_OUTPUT.PUT_LINE('Entre em contato com o administrador. ');
			DBMS_OUTPUT.PUT_LINE('Código Oracle: ' || SQLCODE);
			DBMS_OUTPUT.PUT_LINE('Mensagem Oracle: ' || SQLERRM);
END;
