--CRIAÇÃO DA TABELA DE LOG
CREATE TABLE TPLOGUSURCLI (	
				 
                 CODUSURNEW INT
				,CODUSUROLD INT
				,CODCLINEW INT
                ,CODCLIOLD INT
				,CODUSURPADRAONEW INT
                ,CODUSURPADRAOOLD INT
                ,DATAALTER DATE
			    ,ENVIAFVNEW VARCHAR2(1)
                ,ENVIAFVOLD VARCHAR2(1)
				,MAQUINA VARCHAR2(80)
			    ,USUARIO VARCHAR2(80)
				,PROGRAM VARCHAR2(80)
			    ,OPERACAO VARCHAR2(1)
                  );

CREATE TABLE TPLOGUSURCLI2 (	
				 
                 CODUSURNEW INT
				,CODUSUROLD INT
				,CODCLINEW INT
                ,CODCLIOLD INT
				,CODUSURPADRAONEW INT
                ,CODUSURPADRAOOLD INT
                ,DATAALTER DATE
			    ,ENVIAFVNEW VARCHAR2(1)
                ,ENVIAFVOLD VARCHAR2(1)
				,MAQUINA VARCHAR2(80)
			    ,USUARIO VARCHAR2(80)
				,PROGRAM VARCHAR2(80)
			    ,OPERACAO VARCHAR2(1)
                  );
                                     
---- FIM CREATE TABLE       
							  
--INICIO CRIAÇÃO TRIGGER
CREATE OR REPLACE TRIGGER TRG_LOG_PCUSURCLI
AFTER --GATILHO/DEPOIS
INSERT OR UPDATE OR DELETE ON TUPAN.PCUSURCLI --AÇÃO
FOR EACH ROW 
DECLARE 
  VSMAQUINA     VARCHAR2(80);
  VSUSUARIO     VARCHAR2(80);
  VSPROGRAMA    VARCHAR2(80);
  VS_IN_TIPO_OPERACAO  VARCHAR2(1)  := NULL;

BEGIN
  VSMAQUINA  := SUBSTR(SYS_CONTEXT('USERENV', 'TERMINAL'), 1, 80);
  VSUSUARIO  := SUBSTR(SYS_CONTEXT('USERENV', 'OS_USER'), 1, 80);
  VSPROGRAMA := SUBSTR(SYS_CONTEXT('USERENV', 'MODULE'), 1, 80);
   
   IF INSERTING THEN
    VS_IN_TIPO_OPERACAO  := 'I';
  ELSIF UPDATING THEN
    VS_IN_TIPO_OPERACAO  := 'U';
  ELSIF DELETING THEN
    VS_IN_TIPO_OPERACAO  := 'D';
  END IF;
  
      INSERT INTO TPLOGUSURCLI 
      (CODUSURNEW
	  ,CODUSUROLD
	  ,CODCLINEW
      ,CODCLIOLD
	  ,CODUSURPADRAONEW
      ,CODUSURPADRAOOLD
      ,DATAALTER
      ,ENVIAFVNEW
	  ,ENVIAFVOLD
	  ,MAQUINA
	  ,USUARIO
	  ,PROGRAM
	  ,OPERACAO)
      VALUES
      (:NEW.CODUSUR
	  ,:OLD.CODUSUR
	  ,:NEW.CODCLI
      ,:OLD.CODCLI
	  ,:NEW.CODUSURPADRAO
      ,:OLD.CODUSURPADRAO
      ,SYSTIMESTAMP
	  ,:NEW.ENVIAFV
      ,:OLD.ENVIAFV
	  ,VSMAQUINA
	  ,VSUSUARIO
	  ,VSPROGRAMA
	  ,VS_IN_TIPO_OPERACAO);
	  
	  INSERT INTO TPLOGUSURCLI2 
      (CODUSURNEW
	  ,CODUSUROLD
	  ,CODCLINEW
      ,CODCLIOLD
	  ,CODUSURPADRAONEW
      ,CODUSURPADRAOOLD
      ,DATAALTER
      ,ENVIAFVNEW
	  ,ENVIAFVOLD
	  ,MAQUINA
	  ,USUARIO
	  ,PROGRAM
	  ,OPERACAO)
      VALUES
      (:NEW.CODUSUR
	  ,:OLD.CODUSUR
	  ,:NEW.CODCLI
      ,:OLD.CODCLI
	  ,:NEW.CODUSURPADRAO
      ,:OLD.CODUSURPADRAO
      ,SYSTIMESTAMP
	  ,:NEW.ENVIAFV
      ,:OLD.ENVIAFV
	  ,VSMAQUINA
	  ,VSUSUARIO
	  ,VSPROGRAMA
	  ,VS_IN_TIPO_OPERACAO);
	  
	  EXCEPTION 
			WHEN OTHERS THEN  -- SE QUALQUER ERRO OCORRER 
			DBMS_OUTPUT.PUT_LINE('Erro na execução da TRIGGER.');
			DBMS_OUTPUT.PUT_LINE('Entre em contato com o administrador. ');
			DBMS_OUTPUT.PUT_LINE('Código Oracle: ' || SQLCODE);
			DBMS_OUTPUT.PUT_LINE('Mensagem Oracle: ' || SQLERRM);

			
END;
--FIM CRIAÇÃO TRIGGER

-/*SEQUENCE PARA ALIMENTAR O ID DA TABELA DE LOG
CREATE SEQUENCE TUPAN.SEQUENCE_TPLOGUSURCLI_AUTOINCREMENT
	MINVALUE 1
	MAXVALUE 99999999999999999999999999999999999
	INCREMENT BY 1
	START WITH 1; */ 